### ISSUE TITLE
Implement  https://github.com/mailcheck/mailcheck

### ISSUE THREAD

**Issue by Nightapes** [Nightapes/ngx-validators#23]

**Comment by adyba** [comment]
Both email validators are happy with `name@domain` even without TLD.
It could be do done via standard `Validators.pattern(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/)` or even more sophisticated RedEx. 
(this one will not accept today's fancy nTLD's like .mobi, .guru, .club etc. )

**Comment by Nightapes** [comment]
The normal validator uses the HTML5 validation regex. The email _name@domain_ is a valid email (used sometimes in companies). 
What i like from the mailcheck is that it offers corrections for false TLD's. Like: 
![diagram](https://raw.githubusercontent.com/mailcheck/mailcheck/master/doc/example.png)

But i'm unsure if the validator should return the correct value as a proposal or a extra pipe.

**Comment by jcphlux** [comment]
I think this is a very cool idea. No clue how to make it work but vert cool.
