### ISSUE TITLE
Project Question

### ISSUE THREAD

**Issue by davisb10** [Nightapes/ngx-validators#48]
@Nightapes This is an awesome library, however it appears that you have stopped development on it. I was wondering if you would be open to transferring ownership of the repository and the associated npm project, as I would love to take over and work on this project. Please let me know.

Thanks!

**Comment by Nightapes** [comment]
@davisb10  thank you for your message. I had because of private issues not that much time to work on the library. But now i should have more time, and will start working on it again.  But i would appreciate any help and can give you also more rights .

**Comment by davisb10** [comment]
@Nightapes Alright. That sounds perfect. I'd love to help out wherever possible.
