### ISSUE TITLE
fix removeError in Util

### ISSUE THREAD

**Issue by Knoxvillekm** [Nightapes/ngx-validators#52]
When remove last error, errors = {} and control is invalid.
https://stackblitz.com/edit/angular-reactive-forms-xffegp?file=app/app.component.ts

idea:
```
static removeError(control: AbstractControl, errorId: string) {
  if (control.errors && control.hasError(errorId)) {
    if (Object.keys(control.errors).length > 1) {
      delete control.errors[errorId];
    } else {
      control.setErrors(null);
    }
  } 
}
```

**Comment by Nightapes** [comment]
Thanks for the hint @Knoxvillekm 
I changed it in the new release

**Comment by Knoxvillekm** [comment]
Can you export Util?

**Comment by Nightapes** [comment]
@Knoxvillekm it is now exported, check version `4.1.0`
