### ISSUE TITLE
min and max validation are not working when validator @input value change

### ISSUE THREAD

**Issue by sic-sic** [Nightapes/ngx-validators#66]
when I initialize [min] or [max] with some variable, Validation wont work if the variable value change.
For example :
```
<input name="numberOfDays" [max]="myMax"  #numberOfDays="ngModel" />
<span *ngIf="numberOfDays.hasError('max')">Should be lower or equal to {{ myMax }}</span>
```
If `myMax` value change, it wont be considered. The initial value will still be used.

After doing investigations in the source code, I realized the problem is that `ngOnInit()` is called once when angular instantiate the validator. And `this.validator` is being initiated in `ngOnInit()` method with min or max initial value like this.

```
@Directive({
    ...
})
export class MinValidatorDirective implements Validator, OnInit {
    @Input() min: number;

    private validator: ValidatorFn;
    
    ngOnInit() {
        this.validator = UniversalValidators.min(this.min);
    }
    ...
}
```
So now, if `@Input() min` value change, nothing will happen as the `ngOnInit()` method wont be called again.

A possible solution to this is to reassign `this.validator` whenever the `@Input() min` value change.

This a working example:
```
@Directive({
    ...
})
export class MinValidatorDirective implements Validator, OnInit, OnChanges {
    @Input() min: number;

    private validator: ValidatorFn;
    private onChange: () => void;

    ngOnInit() {
        this.validator = UniversalValidators.min(this.min);
    }

    validate(c: AbstractControl): { [key: string]: any } {
        return this.validator(c);
    }
    
    registerOnValidatorChange(fn: () => void): void {
        this.onChange = fn;
    }
    
    ngOnChanges(changes: SimpleChanges): void {
        if ('min' in changes) {
            this.validator = UniversalValidators.min(this.min);
            if (this.onChange) this.onChange();
        }
    }
}
```

And I am calling `this.onChange()` for telling angular to run validation on this formControl since it wont be automatic.

**Comment by Nightapes** [comment]
Hey, thanks for the hint. I never had the usecase to change the value on runtime.
If you want you can make a PR or i will implement it soon

**Comment by raviagrawal86** [comment]
hey, I am facing this exact same issue. Do you know when will you be able to get to this issue... thanks in advance
