### ISSUE TITLE
Calling  before registerOnValidatorChange is called causes an error

### ISSUE THREAD

**Issue by RoopeHakulinen** [Nightapes/ngx-validators#75]
I've been using the `isInRange` for quite some time already and it's worked great. Though, after moving to Angular 9 (I think) I've started to get an error as follows:

```
custom-error-handler.ts:11 TypeError: this.onChange is not a function
    at IsInRangeValidatorDirective.ngOnChanges (ngx-validators.js:963)
    at IsInRangeValidatorDirective.wrapOnChangesHook_inPreviousChangesStorage (core.js:27058)
    at callHook (core.js:4712)
    at callHooks (core.js:4672)
    at executeInitAndCheckHooks (core.js:4612)
    at selectIndexInternal (core.js:9661)
    at Module.ɵɵadvance (core.js:9622)
    at GroupSettingsComponent_Template (group-settings.component.html:46)
    at executeTemplate (core.js:12046)
    at refreshView (core.js:11893)
```

which points to [this part of code](https://github.com/Nightapes/ngx-validators/blob/master/src/components/universal/universal.directive.ts#L117):

```
 ngOnChanges(changes: SimpleChanges): void {
    if (changes["minValue"] || changes["maxValue"]) {
      this.validator = UniversalValidators.isInRange(
        changes["minValue"].currentValue,
        changes["maxValue"].currentValue
      );
      this.onChange(); // Line 963
    }
  }
```

Based on some debugging this is caused by the fact that `registerOnValidatorChange` is called only after the `ngOnChanges` is called. 

The odd thing about this is that it works in some views and not in other even though I cannot see any obvious difference between the views. 

While I don't have a reproduction case available to this, I can grant access to my project for debugging purposes if that helps.

**Comment by Nightapes** [comment]
Thank you for the error, i found the issue and will release soon a new version
See #76

**Comment by RoopeHakulinen** [comment]
Looks annoying the way it needs to be done. Did you figure what has changed in Angular out of interest?

**Comment by Nightapes** [comment]
@RoopeHakulinen  can you try version: ` v5.2.1`

I think the issue is, that is not guaranteed that onChange ist set before the first ngOnChanges.

**Comment by RoopeHakulinen** [comment]
Thanks for getting this sorted out so fast. Everything seems to be working great now with 5.2.1!
